
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secret
spec:
  provider: azure
  secretObjects:                             
  - data:      
    - key: mysql-user                          
      objectName: mysql-user
    - key: mysql-pass                          
      objectName: mysql-pass                      
    secretName: dbsecret                    
    type: Opaque  
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "40c38cae-73af-419a-8ce5-62d20acc0044"
    keyvaultName: "kvspr"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: mysql-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: mysql-pass
          objectType: secret
          objectVersion: "" 
    tenantId: "ed10ace5-fd47-4660-bc91-7c764a302f4f"

